module.exports = {
  docsSidebar: [
    {
      type: 'category',
      label: '旧约',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'old-testament',
        },
      ],
    },
    {
      type: 'category',
      label: '新约',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'new-testament',
        },
      ],
    },
  ],
};
